---
title: "Automatically Publish Quarto Slides with GitHub Actions"
author: "Rose Hartman"
institute: "Children's Hospital of Philadelphia, Arcus Education"
date: "2024-06-13"
---

## What we're covering today

::: {.incremental}

* Very brief intro to Quarto
* Slightly longer intro to GitHub Actions
* Walk through an example of how to set up a repository to publish slides automatically!
* Some resources for you to explore on your own
* NOT covering how to create a GitHub repository or how to use git

:::

::: notes

This is a brief talk, so I'm going to skip past a lot of the basics in the interest of time.
In particular, I'm going to assume you already use git for version control, and are familiar with terms like "commit", "push", and "branch" as they relate to git and GitHub. 
If you're new to git, GitHub, or both, this talk probably won't make a ton of sense for you today, but keep an eye out for the resources at the end and you can bookmark these slides to come back to at a later date. And welcome to the wonderful world of git. 

::: 

# What is Quarto?

::: notes

I'm assuming most of the people listening to this talk have at least heard of Quarto, but to make sure we're all on the same page: Quarto is an open source publishing system, like R Markdown, but with some excellent new functionality.
One thing I particularly like quarto for is slides. This presentation is a quarto file, as a matter of fact!
Quarto files are built for literate statistical programming, meaning you can have executable code blocks and bits of markdown text together in the same file. 
Let's take a quick look at what a single slide in a quarto presentation might look like.

:::

## Quarto example

```{r}
#| message: false
#| code-line-numbers: "|4|5|"
library(tidyverse)
msleep <- msleep |>
  mutate(across(
    where(is.character), 
    as.factor))
```

::: notes

The quarto format provides a lot of great functionality for including code in your presentations, such as line highlighting! 

:::

## Under the hood...

````
## Quarto example

```{{r}}
#| message: false
#| code-line-numbers: "|4|5|"
library(tidyverse)
msleep <- msleep |>
  mutate(across(
    where(is.character), 
    as.factor))
```

::: notes

The quarto format provides a lot of great functionality for including 
code in your presentations, such as line highlighting! 

:::
````

::: notes

And here's what that slide we just saw looks like in the raw quarto file. 
You can see there's a header, "Quarto example", which gives the title of this slide.
And then I have a block of R code, which runs when I render this presentation; this particular block doesn't produce any output, it just changes the msleep dataframe.
There are some options I've specified for the code block, special comments starting with #|. 
The first tells it to suppress messages, so I don't have the message info from loading the tidyverse printed on my slides; this is just like adding "message=FALSE" to a code block in RMarkdown. 
The second, code-line-numbers, is quarto-specific. It's saying I'd like to highlight different lines in the code block sequentially, so I can draw my audience's attention to specific parts of my code. It starts with all lines, then just line 4, then just line 5, then all lines again. 
And under the code block, you can see there's a little section marked "notes" -- that creates the speaker notes for my slides, what I'm reading right now! Notes only show up if you opt to look at a presentation in speaker view.

:::

## Basic workflow to create and publish Quarto slides

::: incremental

* Make changes to your .qmd file(s), previewing with the Render button in RStudio to convert your .qmd file(s) into the final format.
* Run `quarto publish` in the command line (not R console) to put your slides on QuartoPub, or wherever else you want to publish them (note that this also re-renders by default before publishing).

:::

::: notes

Note that this doesn't mention git or GitHub. 
This is just the instructions to render and publish quarto slide decks.
But you probably do also want to version control your work, and you probably do also want to share your .qmd files, in case someone else might want to adapt them. 
So chances are, you have a git and GitHub workflow you need to do in addition to this quarto workflow. 
The beauty of GitHub actions is that you can get half of this work done for you automatically!

::: 

# What are GitHub Actions (GHA)?

::: notes

GitHub Actions are basically magic. 
Briefly, you can set up all kinds of code to run automatically, triggered by events in your GitHub repository. 
This is very flexible, and very powerful, and people use GHAs for all kinds of things. 
Some of the most common examples are about enforcing standards for a repository -- for example, you can set up a GHA that checks any incoming commits to make sure files have alt text for every image, or to make sure each commit message mentions an issue number. 
But it can do so much more, including running automatic tests on your R code, updating your pkgdown website, etc.

::: 

## {{< fa book-open >}} Learn about GitHub Actions

Read the [GitHub Actions Quickstart Guide](https://docs.github.com/en/actions/quickstart) and the post on the Tidyverse blog about [GitHub Actions for R Users](https://www.tidyverse.org/blog/2022/06/actions-2-0-0/).

<br>

If you want a dive off the deep end, watch this talk about how data scientists leverage GH Actions in a machine learning analysis workflow: [Machine learning operations with GitHub Actions and Kubernetes](https://www.youtube.com/watch?v=Ll50l3fsoYs)

::: notes

These are some links for you to come back to later if you want to learn more about GHA. 

::: 

## Anatomy of a GHA

A YAML file saved in `.github/workflows`

<br>

```
on:
  [Whatever event you want to be the trigger]
  
name: [What is this action called?]

jobs: 
  [What should be done? This includes both the "steps" and the "runner" -- the virtual machine the steps should be run on.]

```

::: notes

The directory `.github/workflows` is special, and any YAML files you save in there GH will try to use as actions. 
The basic structure of a GH Action YAML file is to specify the trigger, which might be something like "whenever a new issue is created" or "whenever someone attempts to merge a branch into main" or even "every Tuesday morning at 6am", the name of the action, and then the jobs that should happen on that trigger -- this could be one thing, but it's often several steps. And there are lots and lots of example workflows ready to use, so you don't have to write code from scratch to execute most things here! You can just say "do the workflow specified in this other public repo over here but on my files". 

::: 

## The GHA + QuartoPub workflow

::: incremental

* Make changes to your .qmd file(s), previewing with the Render button in RStudio as you work.
* When you're ready to commit, render again first with the Render button or run `quarto render` in the command line (not R console). 
* If you **do** want those changes published, commit to main. If you **don't** want them published, commit to a branch.
* As soon as you push changes to main in your GH repo, it triggers the quarto publish action!

:::


::: notes

Your slides will always reflect the current version of your files on main -- there's no risk of you making updates but forgetting to publish them to quartopub.

Note that this is especially handy for repos with multiple collaborators. If you're working on slide decks with someone who is new to quarto and/or doesn't have their own quartopub account set up, you can set it all up once for the whole team and no one has to think about it ever again.

::: 

## The setup

In your directory, you will want:

* `_quarto.yml`
* `_publish.yml`
* `_freeze`
* `.github/workflows`

::: notes

So, if you want your repo to work like that, what do you need to do?

::: 

## `_quarto.yml`

This file sets options for what happens when you render. 

. . . 

Here's what the `_quarto.yml` file for this repo looks like:

```
project:
  type: website
  render: 
    - "*.qmd"
  
embed-resources: true
execute:
  echo: true
  freeze: auto
format: 
  chopr-revealjs  
```

## `_publish.yml`

This file contains the information needed to publish your slides to QuartoPub (except authentication, which has to be set up separately). 
You don't create this file, it will be created automatically the first time you run `quarto publish` locally.

. . . 

Here's what `_publish.yml` looks like in this repo:

```
- source: project
  quarto-pub:
    - id: a8d7fe1c-8a63-40cf-a107-999ae9475df3
      url: 'https://rosemhartman.quarto.pub/rmed_2024'

```

::: notes

Crucially, you won't be able to get this file until you've run quarto publish once successfully on your own computer. That means your first time publishing this document can't be in a GHA; you have to publish it at least once the regular way, and then you can automate all your updates from then on.

::: 

## `_freeze`

You don't create this directory -- quarto will make it for you the first time you render your slides.

. . . 

We have [freeze computations](https://quarto.org/docs/publishing/quarto-pub.html#freezing-computations) set up in `_quarto.yml`. 
This means computations in R are done locally only, and the results are stored in `_freeze`. 

That folder needs to be version controlled so it's available on GitHub. 
When you render, it will save the results of all the executed code in the `_freeze` directory. 
When you commit and push the changes you made to your .qmd file, be sure to add any changes to the `_freeze` directory as well. 

::: notes

We're not asking GitHub to actually execute all the R code (that would be very computationally expensive), so it's important that you use `quarto render` locally on your own computer after making any changes that could affect code output. 

:::

## `.github/workflows`

(From [the Quarto docs instructions for using GHA](https://quarto.org/docs/publishing/quarto-pub.html#publish-action))

```
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
```

::: notes

Here's a look at what my GH Action YAML looks like for this repository. 
This has the same basic structure we talked about for GHA before: on, name, jobs.
The name of this action is Quarto Publish, and it's triggered whenever any contributor pushes changes to main, or it can be triggered manually (that's what workflow_dispatch means).
Under jobs, you can see there are three distinct steps, and for each of them I'm just referencing an existing GH Action somewhere else. 
The first step is "[Check out repository](https://github.com/actions/checkout)" which just gets a copy of the files in the repository ready to work with on the runner. 
The second step is "[Set up Quarto](https://github.com/quarto-dev/quarto-actions/blob/main/setup)" which installs quarto on the runner. 
The third step is "[Render and Publish](https://github.com/quarto-dev/quarto-actions/blob/main/publish)" which publishes my slides to quarto-pub (the target) using my quarto pub authorization token, which has to be stored in secrets for this job to be able to run.
Under each job, the "uses" field points to the example workflow I'm using for each -- the first is just from the general GitHub examples, and the second two are published by the Quarto development team. 

::: 

## QuartoPub authorization

In order for this to work, you need to [create a Quarto Pub personal access token and then configure your GitHub action to be able to read it](https://quarto.org/docs/publishing/quarto-pub.html#quarto-pub-credentials).

. . . 

1. Log in to your **Quarto Pub** account profile page, and click "New Token". Copy it.
2. In your **GitHub** repo, go to Settings > Secrets > Actions and click "New repository secret". Name it `QUARTO_PUB_AUTH_TOKEN` and paste in the token you copied.  

## That's it! {{< fa rocket >}}

Once you have those pieces in place, whenever you update your .qmd files on the main branch of your repo, your slides on Quarto Pub will update, too. 

## {{< fa book-open >}} Keep learning

* You actually didn't need to listen to this talk at all! You can just follow [the Quarto team's instructions for setting up GH actions](https://quarto.org/docs/publishing/quarto-pub.html#github-action).
* To see a practical example, check out the [workshop series we ran using this workflow](https://arcus.github.io/r102/), including slides and recordings for four R workshops. Then poke around the GH repo to see how it's set up!
* Read about how (and why) to [version control your writing](https://education.arcus.chop.edu/version-control-writing/).
* Get started with [Quarto slide decks](https://quarto.org/docs/presentations/).
* Get started with [GitHub Actions](https://docs.github.com/en/actions/quickstart).
* I kept talking about "YAML" and never explained -- [what is YAML?](https://www.redhat.com/en/topics/automation/what-is-yaml)
* New to version control? Check out the Arcus Education [intro to version control](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/Arcus_Labs_Orientation/main/new_to_version_control.md#1), written with biomedical researchers and clinicians in mind.
